// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcMCDxda-C31vkQ6hYQ1wVtNDe25mifQ',
    appId: '1:312661155026:web:51857d43536cb800f2e10b',
    messagingSenderId: '312661155026',
    projectId: 'telecomvc-4d4ce',
    authDomain: 'telecomvc-4d4ce.firebaseapp.com',
    storageBucket: 'telecomvc-4d4ce.firebasestorage.app',
    measurementId: 'G-CHD3Z2FM25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6F0IeoVdJ6aAwOJ9v12qSofiFJRJCwv8',
    appId: '1:312661155026:android:bebc5d389728aef3f2e10b',
    messagingSenderId: '312661155026',
    projectId: 'telecomvc-4d4ce',
    storageBucket: 'telecomvc-4d4ce.firebasestorage.app',
  );
}
